services:

  backend:
    build: ./backend
    container_name: food-truck-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://2300031018:Qwerty9246@@cluster0.xq0oxmn.mongodb.net/smart-food-truck?retryWrites=true&w=majority
      - JWT_SECRET=2300031018
      - REDIS_DISABLED=true

  frontend:
    build: ./frontend
    container_name: food-truck-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
